#!/bin/bash
set -eo pipefail

if [ $# -eq 0 ]
  then
    echo "Usage: $0 COMMIT YOUR-MNT"
    exit
fi

BASE="$(readlink -f "$0" 2>/dev/null || python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$0")"
BASE="$(dirname "$BASE")"
cd "$BASE" || exit 1

git diff --name-only $1 | while IFS='/' read -ra LINE; do
if [[ "${LINE[0]}" = "data" ]]; then
	utils/schema-check/dn42-schema.py -v policy ${LINE[1]} ${LINE[2]} $2
fi
done
