#!/bin/sh

if [ "$#" -eq "0" ]
  then
    echo "Usage: $0 YOUR-MNT"
    exit
fi

if [ "$1" = "--all" ]
then
   MNT=""
else
   MNT="-m $1"
fi

BASE="$(realpath "$0")"
BASE="$(dirname "$BASE")"
cd "$BASE" || exit 1

utils/schema-check/dn42-schema.py -v scan data/ $MNT || ( echo "Schema validation failed, please check above!" ; exit 1 )

