#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "Usage: $0 YOUR-MNT"
    exit
fi

BASE="$(realpath "$0")"
BASE="$(dirname "$BASE")"
cd "$BASE" || exit 1

# utils/schema-check/dn42-schema.py -v scan data/ -m "$1" || ( echo "Schema validation failed, please check above!" ; exit 1 )

git diff --cached --name-only | while IFS='/' read -ra LINE; do
if [[ "${LINE[0]}" = "data" ]]; then

	echo ${LINE[1]} ${LINE[2]}
	utils/schema-check/dn42-schema.py -v policy ${LINE[1]} ${LINE[2]} $1

fi
done
