#!/bin/sh
set -eo pipefail

if [ $# -eq 0 ]
  then
    echo "Usage: $0 COMMIT YOUR-MNT"
    exit
fi

BASE="$(realpath "$0")"
BASE="$(dirname "$BASE")"
cd "$BASE" || exit 1

git diff --name-only $1 | while IFS='/' read -ra LINE; do
if [[ "${LINE[0]}" = "data" ]]; then
	utils/schema-check/dn42-schema.py policy ${LINE[1]} ${LINE[2]} $2
fi
done
