#!/bin/sh

if [ "$#" -eq "0" ]
  then
    echo "Usage: $0 YOUR-MNT"
    exit
fi

BASE="$(realpath "$0")"
BASE="$(dirname "$BASE")"

grep -lr $1 $BASE/data/ | while read line; do utils/schema-check/dn42-schema.py fmt -i $line; done
