#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "Usage: $0 YOUR-MNT"
    exit
fi

BASE="$(realpath "$0")"
BASE="$(dirname "$BASE")"
cd "$BASE" || exit 1

cat >> .git/hooks/pre-commit <<EOF
#!/bin/sh
./check-my-stuff "$1"

# Fail if not everything is PASS
./check-my-stuff JRB0001-MNT 2>/dev/null | grep -v PASS 1>/dev/null 2>&1 && { echo "Schema validation failed, please check above!" 1>&2; exit 1; }
EOF
chmod +x .git/hooks/pre-commit

